ocnao_homepage:
    path:     /
    defaults: { _controller: OCNAOBundle:Home:index }
ocnao_observation:
    path:     /observation
    defaults: { _controller: OCNAOBundle:Observation:observation }
ocnao_recherche:
      path:     /recherche
      defaults: { _controller: OCNAOBundle:Observation:recherche }
ocnao_backoffice:
    path:     /backoffice
    defaults: { _controller: OCNAOBundle:BackOffice:index }
ocnao_contact:
    path:     /contact
    defaults: { _controller: OCNAOBundle:Contact:contact }
