ocnao_homepage:
    path:     /
    defaults: { _controller: OCNAOBundle:Home:index }
ocnao_observation:
    path:     /
    defaults: { _controller: OCNAOBundle:Observation:observation }
ocnao_backoffice:
    path:     /
    defaults: { _controller: OCNAOBundle:BackOffice:index }
ocnao_contact:
    path:     /
    defaults: { _controller: OCNAOBundle:Contact:contact }
