ocnao_homepage:
    path:     /
    defaults: { _controller: OCNAOBundle:Home:index }
ocnao_addObservation:
    path:     /addObservation
    defaults: { _controller: OCNAOBundle:Observation:addObservation }
ocnao_observation:
    path:     /observation/{id}
    defaults: { _controller: OCNAOBundle:Observation:observation }
ocnao_recherche:
    path:     /recherche
    defaults: { _controller: OCNAOBundle:Observation:recherche }
ocnao_backoffice:
    path:     /backoffice
    defaults: { _controller: OCNAOBundle:BackOffice:index }
ocnao_contact:
    path:     /contact
    defaults: { _controller: OCNAOBundle:Contact:contact }
ocnao_autocomplete:
    path:     /autocomplete
    defaults: { _controller: OCNAOBundle:Observation:autocomplete }
    requirements:
      _method: POST
ocnao_backoffice_naturalist:
    path:     /backoffice/naturalist
    defaults: { _controller: OCNAOBundle:BackOffice:naturalist }
    # a supprimer
ocnao_backoffice_nat:
    path:     /backoffice/nat
    defaults: { _controller: OCNAOBundle:BackOffice:nat }
ocnao_backoffice_adm:
    path:     /backoffice/adm
    defaults: { _controller: OCNAOBundle:BackOffice:adm }
ocnao_backoffice_obs:
    path:     /backoffice/obs
    defaults: { _controller: OCNAOBundle:BackOffice:obs }
#  fin suppresion
