<?php

namespace OC\NAOBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
  public function lastObs() {
    $qb = $this->createQueryBuilder('e');
    $qb->where('e.status = 1')->orderBy('e.datetime', 'DESC')->setMaxResults(5);

    return $qb->getQuery()->getResult();
  }

  public function listeObsEspece($espece) {
    $qb = $this->createQueryBuilder('o');
    $qb->select('o')->where('o.taxrefname = :espece')->setParameter('espece', $espece)->orderBy('o.datetime', 'DESC')->andWhere('o.status = 1');

    return $qb->getQuery()->getResult();
  }
}
